### ISSUE TITLE
Incorrect Spd growth on +6 H!F!Corrin

### ISSUE THREAD

**Issue by abdoufma** [Eskuero/fehbuilder#14]
Hi,
I noticed an innacuracy regarding +6 H!F!Corrin's stats in the builder.
[She gets +1 HP and +1 Spd when she's +6](https://imgur.com/a/pgJbfom)
The builder incorrectly says she gets +1 HP/+1 Atk

Hope this helps.

**Comment by Eskuero** [comment]
Please confirm what stat your Corrin has ascended and which has an IV on it.

If you had +Atk IV and ascended her speed the correct stat is 68 Atk and 53 Speed
If you had +Spd IV and ascended her attack the correct stat is 67 Atk and 54 Speed.

This is because ascended boosts do not affect the order in which dragonflower and merges stats are given.

**Comment by abdoufma** [comment]
You are correct! My Corrin is indeed +Spd.
I was not aware that ascended stats affected stat distribution differently from regular assets.
Thanks for clarifying.

**Comment by Eskuero** [comment]
You are welcome :)
