### ISSUE TITLE
Tiki: Legendary Dragon cannot equip Passive C Skill, "With Everyone!" or "With Everyone! II" if her weapon is "Arcane Grima"

### ISSUE THREAD

**Issue by GoofGarage** [Eskuero/fehbuilder#15]
In the Unit Builder, if "Tiki: Legendary Dragon" is selected, if the specific weapon "Arcane Grima" is equipped, Tiki cannot be given the "With Everyone!" or "With Everyone! II" Passive C Skills.  This only seems to affect the weapon, "Arcane Grima".  Weapons other than "Divine Mist" outside of "Arcane Grima" can be selected, and her non-inheritable C skills can still be selected.

**Comment by Eskuero** [comment]
This is intentional because it's how it works in the base game. Units who weren't the original user of the Arcane weapon are disabled from equipping their own prf skills if the have an Arcane weapon equipped.

You can see the same behaviour with per example legendary Ike, equipe Arcane Devourer and you will see you can no longer use Radiant Aether.

You can bypass this enabling the "Cheats" checkbox.
