### ISSUE TITLE
A missing PRF weapon and a missing skill

### ISSUE THREAD

**Issue by CrossKujikawa** [Eskuero/fehbuilder#4]
Hello, I'd like to report two missing skills from Charlotte's base kit:
- "Fair-Fury Axe"
- "Frenzy 3"

**Comment by Eskuero** [comment]
Thanks to your report!

Yes I'm aware of this, all skills and weapons added with the latest banner are missing because the wiki has not created them yet (they are lsited but not defined). As stated this builder grabs all the data it needs by querying the Wiki API so until they update their tables and then my scripts obtain the new info they won't be available.

A sample request I do for skills list from the wiki is like this, and as you can see per example the family of AR-D Atk/Spd only go up until the tier 3 one for now.
https://feheroes.fandom.com/api.php?action=cargoquery&tables=Skills&fields=group_concat(Name)=FamilyMembers,SP,Scategory&group_by=GroupName&limit=max&offset=0&format=json

When the wiki updates I could force my scripts to grab all the new data, even if I can't in that particular moment the server is automated to refresh the data once a day.

Gonna leave this issue open until the data is available to avoid duplicates.

**Comment by CrossKujikawa** [comment]
Alright, thanks!

**Comment by Eskuero** [comment]
Fixed in https://github.com/Eskuero/fehbuilder/commit/1d88eee22c9a118d4b7de7d5d95b3afe61e3ee68
