### ISSUE TITLE
Change unit rarity

### ISSUE THREAD

**Issue by CrossKujikawa** [Eskuero/fehbuilder#5]
Just out of curiosity...will we be getting the ability to change a unit's ★ rating in the future, or will we have to use their maximum of 5★?

- Cross

**Comment by Eskuero** [comment]
What's the usecase for this? I didn't implement it from the get-go because I guessed nobody builds 4 stars anymore since it's impossible to use them in arena for scoring.

Making the change to calculate the stats correctly should be easy. Modifying the base images would be more annoying since I hardcoded them to show the 5 stars line
https://github.com/Eskuero/fehbuilder/blob/master/data/img/base/foreground.png

**Comment by CrossKujikawa** [comment]
I forget the original 4★ code text, so I'll update you on it when I find it. As for the Arena, I have several 4★ heroes that I find use for.

**Comment by Eskuero** [comment]
Just leave it open and I will come back to this at some point :) Right now I've other things I need to fix first

**Comment by CrossKujikawa** [comment]
> Just leave it open and I will come back to this at some point :) Right now I've other things I need to fix first

Sure!

**Comment by Eskuero** [comment]
Add support for 4* and all rarities on https://github.com/Eskuero/fehbuilder/commit/186ed16239ee2db89cb0f82c2d256935d56239a3
